"""Verifier-only exact-snapshot replication conformance support.

The primary sample application is generated by the selected coding CLI. This separate
proof replays already frozen framework bytes through lifecycle adapters and never claims
that a coding CLI or model authored those bytes.
"""

from __future__ import annotations

import hashlib
import importlib.metadata
import json
import os
import stat
import sys
from pathlib import Path

from literate_ai.adapters.builders import BuildError, run_bounded_process
from literate_ai.adapters.dependencies import (
    DependencyObservationError,
    installed_python_distribution_payload,
    observe_installed_python_distributions,
)
from literate_ai.contracts import (
    CYCLONEDX_SOURCE_SBOM_PATH,
    ContentReference,
    canonical_json_bytes,
)
from literate_ai.self_hosting import FrozenPackageTree, run_snapshot_replication

_INTERPRETER_LAYOUT_SCHEMA = "literate-ai/python-interpreter-layout@1"
_INTERPRETER_LAYOUT_TIMEOUT_SECONDS = 10
_MAX_INTERPRETER_LAYOUT_BYTES = 16 * 1024
_MAX_INTERPRETER_LAYOUT_STDERR_BYTES = 8 * 1024
_MAX_INTERPRETER_PATH_CHARACTERS = 4096
_MAX_INTERPRETER_SYS_PATHS = 64
_MAX_STANDARD_LIBRARY_ROOTS = 4
_MAX_DENIED_PACKAGE_ROOTS = 4
_PACKAGE_DIRECTORY_NAMES = frozenset({"site-packages", "dist-packages"})

_INTERPRETER_LAYOUT_PROBE = r"""
import json
import sys
import sysconfig

base_variables = {
    'base': sys.base_prefix,
    'platbase': sys.base_exec_prefix,
    'installed_base': sys.base_prefix,
    'installed_platbase': sys.base_exec_prefix,
}
base_paths = sysconfig.get_paths(vars=base_variables)
active_paths = sysconfig.get_paths()

def origin(module):
    spec = getattr(module, '__spec__', None)
    return {
        'file': getattr(module, '__file__', None),
        'origin': getattr(spec, 'origin', None),
    }

print(json.dumps({
    'schema': 'literate-ai/python-interpreter-layout@1',
    'executable': sys.executable,
    'base_prefix': sys.base_prefix,
    'base_exec_prefix': sys.base_exec_prefix,
    'implementation': sys.implementation.name,
    'platform': sys.platform,
    'flags': {
        'isolated': sys.flags.isolated,
        'no_site': sys.flags.no_site,
        'safe_path': sys.flags.safe_path,
    },
    'base_paths': {
        name: base_paths.get(name)
        for name in ('stdlib', 'platstdlib', 'purelib', 'platlib')
    },
    'active_package_paths': {
        name: active_paths.get(name)
        for name in ('purelib', 'platlib')
    },
    'sys_path': sys.path,
    'helper_origins': {
        'json': origin(json),
        'sysconfig': origin(sysconfig),
    },
}, ensure_ascii=False, sort_keys=True, separators=(',', ':')))
"""

_PROBE = r"""
import json
import sys
import tempfile
from pathlib import Path

candidate = Path(sys.argv[1]).resolve(strict=True)
original = Path(sys.argv[2]).resolve(strict=True)
sample = Path(sys.argv[3]).resolve(strict=True)
probe_root = Path(sys.argv[4]).resolve()
dependency_projection = Path(sys.argv[5]).resolve(strict=True)
raw_layout = json.loads(sys.argv[6])
if not isinstance(raw_layout, dict) or set(raw_layout) != {
    'stdlib_roots', 'denied_package_roots'
}:
    raise RuntimeError('standard-library root inventory is invalid')
raw_stdlib_roots = raw_layout['stdlib_roots']
raw_denied_roots = raw_layout['denied_package_roots']
if (
    not isinstance(raw_stdlib_roots, list)
    or not raw_stdlib_roots
    or len(raw_stdlib_roots) > 4
    or not isinstance(raw_denied_roots, list)
    or len(raw_denied_roots) > 4
):
    raise RuntimeError('standard-library root inventory is invalid')
stdlib_roots = []
for raw_root in raw_stdlib_roots:
    if not isinstance(raw_root, str) or not raw_root:
        raise RuntimeError('standard-library root inventory is invalid')
    stdlib_root = Path(raw_root).resolve(strict=True)
    if not stdlib_root.is_dir():
        raise RuntimeError(f'standard-library root is not a directory: {stdlib_root}')
    if stdlib_root not in stdlib_roots:
        stdlib_roots.append(stdlib_root)
denied_package_roots = []
for raw_root in raw_denied_roots:
    if not isinstance(raw_root, str) or not raw_root:
        raise RuntimeError('standard-library root inventory is invalid')
    denied_root = Path(raw_root).resolve(strict=True)
    if not denied_root.is_dir():
        raise RuntimeError(f'denied package root is not a directory: {denied_root}')
    if denied_root not in denied_package_roots:
        denied_package_roots.append(denied_root)

# These imports and their complete already-loaded helper closure were resolved before
# generated or projected paths entered sys.path. Prove their locations against the
# parent-validated interpreter inventory before making either path importable.
for name, module in sorted(sys.modules.items()):
    location = getattr(module, '__file__', None)
    if location is None:
        continue
    resolved = Path(location).resolve(strict=True)
    if any(
        resolved.is_relative_to(denied_root)
        for denied_root in denied_package_roots
    ) or any(
        part.casefold() in {'site-packages', 'dist-packages'}
        for part in resolved.parts
    ):
        raise RuntimeError(
            f'interpreter helper came from a package root: {name}={resolved}'
        )
    if not any(resolved.is_relative_to(root) for root in stdlib_roots):
        raise RuntimeError(f'interpreter helper fell outside stdlib: {name}={resolved}')
for entry in sys.path:
    if not entry:
        continue
    resolved = Path(entry).resolve()
    if any(
        resolved == protected or resolved.is_relative_to(protected)
        or protected.is_relative_to(resolved)
        for protected in (
            candidate, original, sample, probe_root, dependency_projection
        )
    ):
        raise RuntimeError(
            f'clean interpreter path overlaps replay authority: {resolved}'
        )
sys.path[:0] = [str(candidate), str(dependency_projection)]

import literate_ai
from literate_ai.adapters.component_markdown import parse_component_markdown
from literate_ai.adapters.specifications import LiterateMarkdownProvider
from literate_ai.application import GenerationOrchestrator
from literate_ai.contracts import canonical_identity
from literate_ai.security import SecurityPolicy
from literate_ai.source_to_specification import load_builtin_skill_catalog
from literate_ai.workspace import WorkspaceTreeStore

component_path = sample / 'component.md'
authoring = parse_component_markdown(
    component_path,
    component_path.read_text(encoding='utf-8'),
    project_root=sample.parent.parent,
)
specification = LiterateMarkdownProvider().load(
    sample,
    authoring.specification_roots,
    id_prefix=f'{authoring.coordinate.namespace}.{authoring.coordinate.name}',
)
specification.require_unchanged(sample)
policy = SecurityPolicy(canonical_identity({'policy': 'candidate-probe'}).uri)
skills = load_builtin_skill_catalog()
if set(skills) != {
    'architecture', 'api-surface', 'behavior-state', 'tests', 'security', 'operations',
    'language-python', 'language-cpp', 'language-rust', 'language-javascript'
}:
    raise RuntimeError('candidate packaged skill resources are incomplete')
workspace = WorkspaceTreeStore(probe_root / 'workspace')
prepared = workspace.prepare({'probe.txt': b'candidate-public-api\n'})
accepted = workspace.commit(prepared, 'probe/public-api')
if workspace.resolve('probe/public-api') != accepted:
    raise RuntimeError('candidate workspace public API did not round trip')
if GenerationOrchestrator.__module__ != 'literate_ai.application.orchestrator':
    raise RuntimeError('candidate GenerationOrchestrator public API is unavailable')

# Audit after the complete public-API exercise so lazy imports cannot escape the proof.
module_root = Path(literate_ai.__file__).resolve().parent.parent
if module_root != candidate:
    raise RuntimeError(f'candidate import fallback: {module_root} != {candidate}')
for entry in sys.path:
    if not entry:
        continue
    resolved = Path(entry).resolve()
    if resolved == original or resolved.is_relative_to(original):
        raise RuntimeError(f'original checkout remained importable: {resolved}')
loaded = []
external_loaded = []
for name, module in sorted(sys.modules.items()):
    location = getattr(module, '__file__', None)
    if location is None:
        continue
    resolved = Path(location).resolve()
    if name == 'literate_ai' or name.startswith('literate_ai.'):
        if not resolved.is_relative_to(candidate):
            raise RuntimeError(f'module fallback outside candidate: {name}={resolved}')
        loaded.append(name)
        continue
    if resolved.is_relative_to(candidate):
        continue
    if resolved.is_relative_to(dependency_projection):
        external_loaded.append(name)
        continue
    if any(
        resolved.is_relative_to(denied_root)
        for denied_root in denied_package_roots
    ) or any(
        part.casefold() in {'site-packages', 'dist-packages'}
        for part in resolved.parts
    ):
        raise RuntimeError(f'undeclared package-root import: {name}={resolved}')
    if any(resolved.is_relative_to(root) for root in stdlib_roots):
        continue
    raise RuntimeError(f'undeclared dependency import: {name}={resolved}')

print(json.dumps({
    'schema': 'literate-ai/snapshot-replication-candidate-conformance@1',
    'api_identity': canonical_identity({
        'component': authoring.identity.to_dict(),
        'specification': specification.specification_set.identity.to_dict(),
        'policy': policy.policy_digest,
        'packaged_skills': [skills[key].ref.content_digest for key in sorted(skills)],
        'workspace_tree': prepared.tree_digest,
    }).uri,
    'loaded_external_module_count': len(external_loaded),
    'loaded_literate_module_count': len(loaded),
    'module_root_is_candidate': True,
    'original_checkout_absent': True,
}, sort_keys=True, separators=(',', ':')))
"""


class SelfHostSampleError(RuntimeError):
    pass


def _path_key(path: Path) -> str:
    return os.path.normcase(str(path))


def _is_filesystem_root(path: Path) -> bool:
    return path.parent == path


def _is_link_like(path: Path) -> bool:
    try:
        metadata = path.lstat()
    except OSError:
        return True
    return stat.S_ISLNK(metadata.st_mode) or bool(
        getattr(metadata, "st_file_attributes", 0) & 0x0400
    )


def _paths_overlap(left: Path, right: Path) -> bool:
    return left == right or left.is_relative_to(right) or right.is_relative_to(left)


def _is_package_directory(path: Path) -> bool:
    return any(part.casefold() in _PACKAGE_DIRECTORY_NAMES for part in path.parts)


def _probe_path(value: object, *, label: str) -> Path:
    if (
        not isinstance(value, str)
        or not value
        or len(value) > _MAX_INTERPRETER_PATH_CHARACTERS
        or "\x00" in value
    ):
        raise SelfHostSampleError(f"interpreter layout has an invalid {label}")
    path = Path(value)
    if not path.is_absolute():
        raise SelfHostSampleError(f"interpreter layout has a relative {label}")
    return path


def _existing_probe_directory(value: object, *, label: str) -> Path:
    raw = _probe_path(value, label=label)
    if _is_link_like(raw):
        raise SelfHostSampleError(f"interpreter layout {label} is linked")
    try:
        resolved = raw.resolve(strict=True)
    except (OSError, RuntimeError) as exc:
        raise SelfHostSampleError(f"interpreter layout {label} is unavailable") from exc
    if not resolved.is_dir() or _is_filesystem_root(resolved):
        raise SelfHostSampleError(f"interpreter layout {label} is unsafe")
    return resolved


def _optional_existing_probe_directory(
    value: object, *, label: str, reject_links: bool = False
) -> Path | None:
    if value is None:
        return None
    raw = _probe_path(value, label=label)
    if reject_links and _is_link_like(raw):
        raise SelfHostSampleError(f"interpreter layout {label} is linked")
    try:
        resolved = raw.resolve(strict=True)
    except OSError:
        return None
    except RuntimeError as exc:
        raise SelfHostSampleError(f"interpreter layout {label} is unavailable") from exc
    if not resolved.is_dir() or _is_filesystem_root(resolved):
        raise SelfHostSampleError(f"interpreter layout {label} is unsafe")
    return resolved


def _validate_interpreter_layout_probe(
    output: bytes,
    *,
    selected_executable: Path,
    protected_roots: tuple[Path, ...],
) -> tuple[tuple[Path, ...], tuple[Path, ...]]:
    """Validate a bounded isolated-interpreter report before trusting its roots."""

    if not isinstance(output, bytes) or len(output) > _MAX_INTERPRETER_LAYOUT_BYTES:
        raise SelfHostSampleError("interpreter layout output exceeds its byte budget")
    try:
        document = json.loads(output)
    except (UnicodeError, json.JSONDecodeError, RecursionError) as exc:
        raise SelfHostSampleError("interpreter layout output is not JSON") from exc
    required = {
        "schema",
        "executable",
        "base_prefix",
        "base_exec_prefix",
        "implementation",
        "platform",
        "flags",
        "base_paths",
        "active_package_paths",
        "sys_path",
        "helper_origins",
    }
    if not isinstance(document, dict) or set(document) != required:
        raise SelfHostSampleError("interpreter layout output has an invalid schema")
    if document["schema"] != _INTERPRETER_LAYOUT_SCHEMA:
        raise SelfHostSampleError("interpreter layout output has an invalid schema")

    try:
        selected = selected_executable.resolve(strict=True)
    except (OSError, RuntimeError) as exc:
        raise SelfHostSampleError("selected Python executable is unavailable") from exc
    if not selected.is_file():
        raise SelfHostSampleError("selected Python executable is unsafe")
    reported_executable = _probe_path(
        document["executable"], label="selected executable"
    )
    try:
        reported_executable = reported_executable.resolve(strict=True)
    except (OSError, RuntimeError) as exc:
        raise SelfHostSampleError(
            "interpreter layout selected executable is unavailable"
        ) from exc
    if reported_executable != selected:
        raise SelfHostSampleError("interpreter layout came from another executable")

    flags = document["flags"]
    if not isinstance(flags, dict) or set(flags) != {
        "isolated",
        "no_site",
        "safe_path",
    }:
        raise SelfHostSampleError("interpreter layout flags are invalid")
    if (
        type(flags["isolated"]) is not int
        or flags["isolated"] != 1
        or type(flags["no_site"]) is not int
        or flags["no_site"] != 1
        or flags["safe_path"] is not True
    ):
        raise SelfHostSampleError("interpreter layout was not isolated")

    implementation = document["implementation"]
    platform = document["platform"]
    if (
        not isinstance(implementation, str)
        or not implementation
        or len(implementation) > 64
        or not isinstance(platform, str)
        or not platform
        or len(platform) > 64
    ):
        raise SelfHostSampleError("interpreter layout runtime identity is invalid")

    base_prefix = _existing_probe_directory(
        document["base_prefix"], label="base_prefix"
    )
    base_exec_prefix = _existing_probe_directory(
        document["base_exec_prefix"], label="base_exec_prefix"
    )
    base_prefixes = tuple(sorted({base_prefix, base_exec_prefix}, key=_path_key))

    raw_sys_path = document["sys_path"]
    if (
        not isinstance(raw_sys_path, list)
        or not raw_sys_path
        or len(raw_sys_path) > _MAX_INTERPRETER_SYS_PATHS
    ):
        raise SelfHostSampleError("interpreter layout sys.path is invalid")
    if not protected_roots or len(protected_roots) > 8:
        raise SelfHostSampleError("interpreter replay authority roots are invalid")
    try:
        protected = tuple(path.resolve() for path in protected_roots)
    except RuntimeError as exc:
        raise SelfHostSampleError(
            "interpreter replay authority root is unavailable"
        ) from exc
    clean_directory_entries: set[Path] = set()
    for index, value in enumerate(raw_sys_path):
        raw_path = _probe_path(value, label=f"sys.path[{index}]")
        try:
            canonical = raw_path.resolve()
        except RuntimeError as exc:
            raise SelfHostSampleError("interpreter layout sys.path is unsafe") from exc
        if any(_paths_overlap(canonical, root) for root in protected):
            raise SelfHostSampleError(
                "isolated interpreter sys.path overlaps replay authority"
            )
        try:
            existing = raw_path.resolve(strict=True)
        except OSError:
            continue
        if existing.is_dir() and not _is_link_like(raw_path):
            clean_directory_entries.add(existing)

    base_paths = document["base_paths"]
    active_paths = document["active_package_paths"]
    if not isinstance(base_paths, dict) or set(base_paths) != {
        "stdlib",
        "platstdlib",
        "purelib",
        "platlib",
    }:
        raise SelfHostSampleError("interpreter layout base paths are invalid")
    if not isinstance(active_paths, dict) or set(active_paths) != {
        "purelib",
        "platlib",
    }:
        raise SelfHostSampleError("interpreter layout package paths are invalid")

    denied_roots: set[Path] = set()
    for owner, paths in (("base", base_paths), ("active", active_paths)):
        for field in ("purelib", "platlib"):
            root = _optional_existing_probe_directory(
                paths[field], label=f"{owner} {field}"
            )
            if root is not None:
                denied_roots.add(root)
    if len(denied_roots) > _MAX_DENIED_PACKAGE_ROOTS:
        raise SelfHostSampleError("interpreter layout has too many package roots")

    candidates: list[tuple[str, Path, bool]] = []
    for field in ("stdlib", "platstdlib"):
        root = _optional_existing_probe_directory(
            base_paths[field], label=f"base {field}", reject_links=True
        )
        if root is not None:
            candidates.append((field, root, False))
    if implementation.casefold() == "cpython" and platform.casefold() == "win32":
        dlls_raw = base_prefix / "DLLs"
        try:
            dlls = dlls_raw.resolve(strict=True)
        except OSError:
            dlls = None
        except RuntimeError as exc:
            raise SelfHostSampleError(
                "interpreter layout Windows DLL root is unavailable"
            ) from exc
        if dlls is not None:
            if _is_link_like(dlls_raw) or not dlls.is_dir():
                raise SelfHostSampleError(
                    "interpreter layout Windows DLL root is unsafe"
                )
            candidates.append(("DLLs", dlls, True))

    roots: dict[str, Path] = {}
    for label, root, windows_dlls in candidates:
        if _is_filesystem_root(root):
            raise SelfHostSampleError(
                f"interpreter layout {label} resolves to a filesystem root"
            )
        if any(_paths_overlap(root, protected_root) for protected_root in protected):
            raise SelfHostSampleError(
                f"interpreter layout {label} overlaps replay authority"
            )
        if _is_package_directory(root) or any(
            root == denied or root.is_relative_to(denied) for denied in denied_roots
        ):
            raise SelfHostSampleError(
                f"interpreter layout {label} is a package-installation root"
            )
        if not any(
            root != prefix and root.is_relative_to(prefix) for prefix in base_prefixes
        ):
            # Virtual-environment platstdlib roots are intentionally not authority
            # for a base-interpreter replay.
            continue
        if root not in clean_directory_entries:
            continue
        if windows_dlls and root.name.casefold() != "dlls":
            raise SelfHostSampleError("interpreter layout Windows DLL root is invalid")
        roots[_path_key(root)] = root
    if not roots or len(roots) > _MAX_STANDARD_LIBRARY_ROOTS:
        raise SelfHostSampleError(
            "selected Python interpreter has no bounded standard-library roots"
        )
    accepted = tuple(roots[key] for key in sorted(roots))

    helper_origins = document["helper_origins"]
    if not isinstance(helper_origins, dict) or set(helper_origins) != {
        "json",
        "sysconfig",
    }:
        raise SelfHostSampleError("interpreter helper provenance is invalid")
    for module_name, raw_origin in helper_origins.items():
        if not isinstance(raw_origin, dict) or set(raw_origin) != {"file", "origin"}:
            raise SelfHostSampleError("interpreter helper provenance is invalid")
        file_path = _probe_path(raw_origin["file"], label=f"{module_name} helper file")
        origin_path = _probe_path(
            raw_origin["origin"], label=f"{module_name} helper origin"
        )
        try:
            file_path = file_path.resolve(strict=True)
            origin_path = origin_path.resolve(strict=True)
        except (OSError, RuntimeError) as exc:
            raise SelfHostSampleError(
                "interpreter helper provenance is unavailable"
            ) from exc
        if file_path != origin_path or not file_path.is_file():
            raise SelfHostSampleError("interpreter helper provenance changed")
        if _is_package_directory(file_path) or any(
            file_path.is_relative_to(root) for root in denied_roots
        ):
            raise SelfHostSampleError(
                "interpreter helper came from a package-installation root"
            )
        if not any(file_path.is_relative_to(root) for root in accepted):
            raise SelfHostSampleError(
                "interpreter helper did not come from the accepted standard library"
            )

    denied = tuple(sorted(denied_roots, key=_path_key))
    return accepted, denied


def _python_standard_library_roots(
    *,
    selected_executable: Path,
    protected_roots: tuple[Path, ...],
    working_directory: Path,
) -> tuple[tuple[Path, ...], tuple[Path, ...]]:
    """Discover base-interpreter roots before adding generated import paths."""

    environment = {
        name: value
        for name, value in os.environ.items()
        if not name.casefold().startswith("python") and name != "__PYVENV_LAUNCHER__"
    }
    try:
        result = run_bounded_process(
            [
                str(selected_executable),
                "-I",
                "-S",
                "-P",
                "-B",
                "-c",
                _INTERPRETER_LAYOUT_PROBE,
            ],
            cwd=working_directory,
            environment=environment,
            timeout_seconds=_INTERPRETER_LAYOUT_TIMEOUT_SECONDS,
            stdout_limit_bytes=_MAX_INTERPRETER_LAYOUT_BYTES,
            stderr_limit_bytes=_MAX_INTERPRETER_LAYOUT_STDERR_BYTES,
            error_prefix="self_host_interpreter_probe",
        )
    except BuildError as exc:
        raise SelfHostSampleError(
            "isolated interpreter layout probe could not complete"
        ) from exc
    if result.returncode != 0:
        raise SelfHostSampleError("isolated interpreter layout probe failed")
    return _validate_interpreter_layout_probe(
        result.stdout,
        selected_executable=selected_executable,
        protected_roots=protected_roots,
    )


def _replication_inputs(sample_root: Path) -> tuple[Path, Path]:
    try:
        harness_manifest = (
            sample_root.parent / "_harness" / sample_root.name / "sample.json"
        )
        if harness_manifest.is_symlink():
            raise OSError("sample harness manifest is a symbolic link")
        metadata = json.loads(harness_manifest.read_text(encoding="utf-8"))
        references = metadata["conformance_proofs"]
        if not isinstance(references, list) or len(references) != 1:
            raise ValueError("expected one conformance proof")
        proof_reference = ContentReference.from_dict(references[0])
    except (OSError, UnicodeError, json.JSONDecodeError, KeyError, ValueError) as exc:
        raise SelfHostSampleError(
            "sample metadata lacks one exact snapshot-replication proof pin"
        ) from exc
    harness_root = harness_manifest.parent
    configured_proof = harness_root / proof_reference.uri
    if (
        proof_reference.kind != "conformance-proof"
        or proof_reference.uri != "conformance/snapshot-replication.json"
        or configured_proof.is_symlink()
        or not configured_proof.is_file()
    ):
        raise SelfHostSampleError("snapshot-replication proof pin is invalid")
    proof_path = configured_proof.resolve(strict=True)
    content = proof_path.read_bytes()
    if hashlib.sha256(content).hexdigest() != proof_reference.identity.digest:
        raise SelfHostSampleError("snapshot-replication proof identity changed")
    try:
        proof = json.loads(content)
        skill_reference = ContentReference.from_dict(proof["skill_set"])
    except (UnicodeError, json.JSONDecodeError, KeyError, ValueError) as exc:
        raise SelfHostSampleError("snapshot-replication proof is invalid") from exc
    if proof.get("coding_cli_involved") is not False:
        raise SelfHostSampleError(
            "snapshot replication must not claim coding-CLI involvement"
        )
    configured_skills = proof_path.parent / skill_reference.uri
    if (
        skill_reference.kind != "snapshot-replication-skill-set"
        or configured_skills.is_symlink()
        or not configured_skills.is_file()
    ):
        raise SelfHostSampleError("snapshot-replication skill pin is invalid")
    skills_path = configured_skills.resolve(strict=True)
    if hashlib.sha256(skills_path.read_bytes()).hexdigest() != (
        skill_reference.identity.digest
    ):
        raise SelfHostSampleError("snapshot-replication skill identity changed")
    return proof_path, skills_path


def _candidate_dependency_projection(
    candidate_root: Path, projection_root: Path
) -> Path:
    source_relative_bom = CYCLONEDX_SOURCE_SBOM_PATH.removeprefix("source/")
    source_bom = candidate_root.joinpath(*source_relative_bom.split("/"))
    try:
        document = json.loads(source_bom.read_text(encoding="utf-8"))
        raw_components = document["components"]
        raw_dependencies = document["dependencies"]
        root_ref = document["metadata"]["component"]["bom-ref"]
    except (KeyError, OSError, TypeError, UnicodeError, json.JSONDecodeError) as exc:
        raise SelfHostSampleError(
            "candidate SOURCE BOM dependency inventory is unavailable"
        ) from exc
    if (
        not isinstance(raw_components, list)
        or not isinstance(raw_dependencies, list)
        or not isinstance(root_ref, str)
        or not root_ref
    ):
        raise SelfHostSampleError("candidate SOURCE BOM dependency graph is invalid")
    expected: dict[str, dict[str, object]] = {}
    coordinates: dict[str, str] = {}
    optional_refs: set[str] = set()
    for raw in raw_components:
        if not isinstance(raw, dict):
            raise SelfHostSampleError(
                "candidate SOURCE BOM contains an invalid component"
            )
        purl = raw.get("purl")
        if not isinstance(purl, str) or not purl.startswith("pkg:pypi/"):
            continue
        ref = raw.get("bom-ref")
        version = raw.get("version")
        coordinate = purl.removeprefix("pkg:pypi/").split("@", 1)[0]
        if (
            not isinstance(ref, str)
            or not ref
            or not isinstance(version, str)
            or not version
            or not coordinate
            or ref in expected
        ):
            raise SelfHostSampleError(
                "candidate SOURCE BOM Python dependency is not exact"
            )
        if raw.get("scope") == "optional":
            properties = raw.get("properties")
            if not isinstance(properties, list):
                raise SelfHostSampleError(
                    "candidate SOURCE BOM optional Python dependency lacks evidence"
                )
            declared = {
                str(item.get("value"))
                for item in properties
                if isinstance(item, dict)
                and item.get("name") == "literate-ai:python-declared-requirement"
                and isinstance(item.get("value"), str)
                and str(item.get("value")).strip()
            }
            records = {
                str(item.get("value"))
                for item in properties
                if isinstance(item, dict)
                and item.get("name") == "literate-ai:python-optional-requirement"
                and isinstance(item.get("value"), str)
                and str(item.get("value")).strip()
            }
            if not declared or not records:
                raise SelfHostSampleError(
                    "candidate SOURCE BOM optional Python dependency lacks evidence"
                )
            for record_text in records:
                try:
                    record = json.loads(record_text)
                except json.JSONDecodeError as exc:
                    raise SelfHostSampleError(
                        "candidate SOURCE BOM optional Python dependency is invalid"
                    ) from exc
                if (
                    not isinstance(record, dict)
                    or set(record) != {"group", "requirement"}
                    or not isinstance(record["group"], str)
                    or not record["group"].strip()
                    or record["requirement"] not in declared
                ):
                    raise SelfHostSampleError(
                        "candidate SOURCE BOM optional Python dependency is invalid"
                    )
            optional_refs.add(ref)
            continue
        expected[ref] = raw
        coordinates[ref] = coordinate
    if not expected:
        raise SelfHostSampleError(
            "candidate SOURCE BOM lacks framework Python dependencies"
        )
    if optional_refs and not all(
        any(
            raw.get("ref") == root_ref
            and isinstance(raw.get("dependsOn"), list)
            and ref in raw["dependsOn"]
            for raw in raw_dependencies
            if isinstance(raw, dict)
        )
        for ref in optional_refs
    ):
        raise SelfHostSampleError(
            "candidate SOURCE BOM optional Python dependency is not root-declared"
        )

    source_edges: set[tuple[str, str]] = set()
    for raw in raw_dependencies:
        if not isinstance(raw, dict):
            raise SelfHostSampleError(
                "candidate SOURCE BOM contains an invalid dependency edge"
            )
        source = raw.get("ref")
        targets = raw.get("dependsOn")
        if not isinstance(source, str) or not isinstance(targets, list):
            raise SelfHostSampleError(
                "candidate SOURCE BOM contains an invalid dependency edge"
            )
        for target in targets:
            if not isinstance(target, str):
                raise SelfHostSampleError(
                    "candidate SOURCE BOM contains an invalid dependency edge"
                )
            if target in expected and (source == root_ref or source in expected):
                source_edges.add((source, target))
    direct_refs = {target for source, target in source_edges if source == root_ref}
    requirements: set[str] = set()
    for ref in direct_refs:
        properties = expected[ref].get("properties")
        if not isinstance(properties, list):
            raise SelfHostSampleError(
                "candidate SOURCE BOM direct Python dependency lacks evidence"
            )
        declared = {
            str(item.get("value"))
            for item in properties
            if isinstance(item, dict)
            and item.get("name") == "literate-ai:python-declared-requirement"
            and isinstance(item.get("value"), str)
            and str(item.get("value")).strip()
        }
        if not declared:
            raise SelfHostSampleError(
                "candidate SOURCE BOM direct Python requirement is missing"
            )
        requirements.update(declared)

    probe_root_ref = "urn:literate-ai:self-host-probe"
    observed = observe_installed_python_distributions(
        tuple(sorted(requirements)), root_ref=probe_root_ref
    )
    inventory = {str(item["bom-ref"]): item for item in observed.components}
    if inventory != expected:
        raise SelfHostSampleError(
            "candidate SOURCE BOM Python inventory is not the exact declared closure"
        )
    normalized_source_edges = {
        (probe_root_ref if source == root_ref else source, target)
        for source, target in source_edges
    }
    if set(observed.edges) != normalized_source_edges:
        raise SelfHostSampleError(
            "candidate SOURCE BOM Python edges are not the exact declared closure"
        )

    if projection_root.exists() and (
        projection_root.is_symlink()
        or not projection_root.is_dir()
        or any(projection_root.iterdir())
    ):
        raise SelfHostSampleError("candidate dependency projection is not clean")
    projection_root.mkdir(parents=True, exist_ok=True)
    projection_root = projection_root.resolve(strict=True)
    # Preserve the wheel installation topology rather than flattening only the
    # importable files into one directory.  RECORD paths for console entry points
    # are relative to site-packages (for example ``../../../bin/jsonschema`` on
    # POSIX), and those files participate in the installed-distribution identity.
    # Three synthetic parents accommodate both POSIX ``bin`` and Windows
    # ``Scripts`` layouts while keeping every destination below projection_root.
    site_packages = projection_root / "lib" / "python-runtime" / "site-packages"
    site_packages.mkdir(parents=True)
    site_packages = site_packages.resolve(strict=True)
    copied_by_distribution: dict[str, int] = {}
    for ref, name in coordinates.items():
        try:
            distribution = importlib.metadata.distribution(name)
            installed_root = Path(distribution.locate_file("")).resolve(strict=True)
        except (importlib.metadata.PackageNotFoundError, OSError) as exc:
            raise SelfHostSampleError(
                "candidate SOURCE BOM Python dependency root is unavailable"
            ) from exc
        if installed_root.is_symlink() or not installed_root.is_dir():
            raise SelfHostSampleError(
                "candidate SOURCE BOM Python dependency root is unsafe"
            )
        copied = 0
        try:
            payload = installed_python_distribution_payload(distribution)
        except DependencyObservationError as exc:
            raise SelfHostSampleError(
                "candidate SOURCE BOM dependency payload is unavailable"
            ) from exc
        for entry_path, resolved_source in payload:
            destination = site_packages.joinpath(*entry_path.parts).resolve()
            if not destination.is_relative_to(projection_root):
                raise SelfHostSampleError(
                    "candidate dependency projection path escaped its root"
                )
            destination.parent.mkdir(parents=True, exist_ok=True)
            content = resolved_source.read_bytes()
            if destination.exists():
                if destination.is_symlink() or destination.read_bytes() != content:
                    raise SelfHostSampleError(
                        "candidate dependency projection contains a file collision"
                    )
            else:
                destination.write_bytes(content)
                destination.chmod(resolved_source.stat().st_mode & 0o777)
            copied += 1
        copied_by_distribution[ref] = copied
    if set(copied_by_distribution) != set(expected) or any(
        count == 0 for count in copied_by_distribution.values()
    ):
        raise SelfHostSampleError(
            "candidate dependency projection is missing distribution files"
        )
    return site_packages


def _environment(candidate_root: Path, dependency_projection: Path) -> dict[str, str]:
    environment = dict(os.environ)
    for name in tuple(environment):
        if name.upper().startswith("PYTHON"):
            environment.pop(name)
    # The proof invokes every nested replay with this interpreter.  Bind discovery to
    # that exact absolute executable as well: an operator may have selected it through
    # a cwd-relative PYTHON value, but the replay deliberately changes working
    # directories and must not reinterpret that spelling there.
    environment["PYTHON"] = str(Path(sys.executable).absolute())
    environment.update(
        {
            "PYTHONDONTWRITEBYTECODE": "1",
            "PYTHONHASHSEED": "0",
            "PYTHONNOUSERSITE": "1",
            "PYTHONPATH": os.pathsep.join(
                (str(candidate_root), str(dependency_projection))
            ),
            "PYTHONUTF8": "1",
        }
    )
    return environment


# A clean replay indexes and qualifies the complete generated framework.
# Hosted Windows filesystems are materially slower than POSIX runners, and a
# Linux worker measured about 480 seconds per candidate, so the outer owner must
# not expire first.
_CANDIDATE_PROCESS_TIMEOUT_SECONDS = (
    900 if os.name == "nt" or sys.platform.startswith("linux") else 300
)
_MAX_CANDIDATE_STDOUT_BYTES = 8 * 1024 * 1024
_MAX_CANDIDATE_STDERR_BYTES = 1024 * 1024
_CANDIDATE_FAILURE_DIAGNOSTIC_BYTES = 64 * 1024


def _candidate_failure_diagnostic(stderr: bytes) -> str:
    if len(stderr) <= _CANDIDATE_FAILURE_DIAGNOSTIC_BYTES:
        selected = stderr
    else:
        boundary = _CANDIDATE_FAILURE_DIAGNOSTIC_BYTES // 2
        omitted = len(stderr) - (boundary * 2)
        selected = (
            stderr[:boundary]
            + f"\n... {omitted} stderr bytes omitted ...\n".encode()
            + stderr[-boundary:]
        )
    return selected.decode("utf-8", errors="replace")


def _run(command: list[str], *, environment: dict[str, str], cwd: Path) -> str:
    try:
        completed = run_bounded_process(
            command,
            cwd=cwd,
            environment=environment,
            timeout_seconds=_CANDIDATE_PROCESS_TIMEOUT_SECONDS,
            stdout_limit_bytes=_MAX_CANDIDATE_STDOUT_BYTES,
            stderr_limit_bytes=_MAX_CANDIDATE_STDERR_BYTES,
            error_prefix="self_host_candidate",
        )
    except BuildError as exc:
        raise SelfHostSampleError(
            "isolated candidate process could not complete"
        ) from exc
    if completed.returncode != 0:
        raise SelfHostSampleError(
            "isolated candidate process failed: "
            + _candidate_failure_diagnostic(completed.stderr)
        )
    try:
        return completed.stdout.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise SelfHostSampleError(
            "isolated candidate process emitted non-UTF-8 output"
        ) from exc


def _probe_candidate(
    candidate_root: Path,
    *,
    original_root: Path,
    sample_root: Path,
    scratch: Path,
) -> dict[str, object]:
    scratch.mkdir(parents=True, exist_ok=True)
    candidate_source = candidate_root / "source"
    if candidate_source.is_symlink() or not candidate_source.is_dir():
        raise SelfHostSampleError("candidate source root is missing or unsafe")
    dependency_projection_root = scratch / "dependencies"
    stdlib_roots, denied_package_roots = _python_standard_library_roots(
        selected_executable=Path(sys.executable),
        protected_roots=(
            candidate_root,
            candidate_source,
            original_root,
            sample_root,
            scratch,
            dependency_projection_root,
        ),
        working_directory=scratch,
    )
    dependency_projection = _candidate_dependency_projection(
        candidate_source, dependency_projection_root
    )
    output = _run(
        [
            sys.executable,
            "-I",
            "-S",
            "-P",
            "-B",
            "-c",
            _PROBE,
            str(candidate_source),
            str(original_root),
            str(sample_root),
            str(scratch),
            str(dependency_projection),
            json.dumps(
                {
                    "stdlib_roots": [str(path) for path in stdlib_roots],
                    "denied_package_roots": [
                        str(path) for path in denied_package_roots
                    ],
                },
                ensure_ascii=False,
                separators=(",", ":"),
            ),
        ],
        environment=_environment(candidate_source, dependency_projection),
        cwd=scratch,
    )
    try:
        value = json.loads(output)
    except json.JSONDecodeError as exc:
        raise SelfHostSampleError("candidate conformance output is not JSON") from exc
    if not isinstance(value, dict):
        raise SelfHostSampleError("candidate conformance output is not an object")
    return value


def _candidate_root(runtime_root: Path, report: dict[str, object]) -> Path:
    digest = report.get("accepted_workspace_tree_digest")
    if not isinstance(digest, str) or not digest.startswith("sha256:"):
        raise SelfHostSampleError("candidate report lacks accepted workspace identity")
    root = runtime_root / "workspace" / "trees" / digest.removeprefix("sha256:")
    if not root.is_dir():
        raise SelfHostSampleError("accepted candidate tree is missing")
    return root


def execute_replication_proof(
    *,
    repo_root: Path,
    sample_root: Path,
    scratch: Path,
    host_build_acknowledged: bool = False,
) -> dict[str, object]:
    """Replay the original snapshot into two independently checked candidates."""

    if not host_build_acknowledged:
        raise SelfHostSampleError(
            "snapshot replication requires explicit unsandboxed host-build "
            "acknowledgement"
        )

    original_package = (repo_root / "src" / "literate_ai").resolve(strict=True)
    original_tree = FrozenPackageTree.capture(original_package)
    component = sample_root / "component.md"
    proof, skills = _replication_inputs(sample_root)
    if sys.platform.startswith("linux"):
        host_os = "linux"
    elif sys.platform == "darwin":
        host_os = "macos"
    elif sys.platform in {"win32", "cygwin"}:
        host_os = "windows"
    else:
        raise SelfHostSampleError(
            f"unsupported snapshot-replication platform: {sys.platform}"
        )
    platform_flavor = repo_root / "flavors" / f"os-{host_os}" / "flavor.md"
    # Keep disposable custody roots short on Windows. Stable evidence uses
    # Windows. Stable evidence uses workspace references and content identities,
    # not these host-local path labels.
    generation_one_root = scratch / "g1"
    generation_one = run_snapshot_replication(
        source_root=original_package,
        component_path=component,
        skills_path=skills,
        proof_path=proof,
        platform_flavor_path=platform_flavor,
        runtime_root=generation_one_root,
        workspace_reference="snapshot-replication/generation-one",
        host_build_acknowledged=host_build_acknowledged,
    )
    probe_one = _probe_candidate(
        generation_one.accepted_root,
        original_root=repo_root,
        sample_root=sample_root,
        scratch=scratch / "p1",
    )

    generation_two_root = scratch / "g2"
    generation_two_source = generation_one.accepted_root / "source"
    generation_two_dependencies = _candidate_dependency_projection(
        generation_two_source, scratch / "g2d"
    )
    output = _run(
        [
            sys.executable,
            "-S",
            "-P",
            "-m",
            "literate_ai.self_hosting",
            "--source-root",
            str(generation_one.accepted_package_root),
            "--component",
            str(component),
            "--skills",
            str(skills),
            "--proof",
            str(proof),
            "--platform-flavor",
            str(platform_flavor),
            "--runtime-root",
            str(generation_two_root),
            "--workspace-reference",
            "snapshot-replication/generation-two",
            "--allow-host-build",
        ],
        environment=_environment(generation_two_source, generation_two_dependencies),
        cwd=scratch,
    )
    try:
        generation_two_report = json.loads(output)
    except json.JSONDecodeError as exc:
        raise SelfHostSampleError("second replay report is not JSON") from exc
    if not isinstance(generation_two_report, dict):
        raise SelfHostSampleError("second replay report is not an object")
    generation_two_candidate = _candidate_root(
        generation_two_root, generation_two_report
    )
    probe_two = _probe_candidate(
        generation_two_candidate,
        original_root=repo_root,
        sample_root=sample_root,
        scratch=scratch / "probe-two",
    )

    first_report = dict(generation_one.stable_outputs)
    if first_report != generation_two_report:
        mismatches = sorted(
            key
            for key in set(first_report) | set(generation_two_report)
            if first_report.get(key) != generation_two_report.get(key)
        )
        raise SelfHostSampleError(
            "second replay semantic outputs changed: " + ", ".join(mismatches)
        )
    final_original_tree = FrozenPackageTree.capture(original_package)
    if original_tree.files != final_original_tree.files:
        raise SelfHostSampleError(
            "original framework snapshot changed while the proof was running"
        )
    first_tree = FrozenPackageTree.capture(generation_one.accepted_package_root)
    second_tree = FrozenPackageTree.capture(
        generation_two_candidate / "source" / "literate_ai"
    )
    if original_tree.files != first_tree.files or first_tree.files != second_tree.files:
        raise SelfHostSampleError("replayed candidate file set or contents changed")
    if probe_one != probe_two:
        raise SelfHostSampleError("candidate public-API conformance was not stable")
    evidence = {
        "schema": "literate-ai/two-generation-snapshot-replication-proof@1",
        "classification": "deterministic-offline-conformance-replay",
        "coding_cli_involved": False,
        "stable_replication": first_report,
        "candidate_conformance": probe_one,
        "replication_count": 2,
        "complete_file_set_stable": True,
        "original_import_fallback": False,
    }
    canonical_json_bytes(evidence)
    return evidence


def main() -> str:
    return "deterministic-two-generation-snapshot-replication"


if __name__ == "__main__":
    repo = Path(__file__).resolve().parents[3]
    sample = Path(__file__).resolve().parent / "self-hosting"
    target = Path.cwd() / ".snapshot-replication-proof"
    print(
        canonical_json_bytes(
            execute_replication_proof(
                repo_root=repo,
                sample_root=sample,
                scratch=target,
                host_build_acknowledged=True,
            )
        ).decode("utf-8")
    )
